### ISSUE TITLE
Glimpse SQL tab showing exception

### ISSUE THREAD

**Issue by lchong0412** [Glimpse/Glimpse#898] opened 2015-04-23 04:29 UTC
It's giving the following error on the SQL tab. I'm using EF 6.1.1 and Glimpse EF6 1.6.5. Do you know what could have caused this issue?

Exception executing tab of type 'glimpse_sql'. | System.NullReferenceException--Object reference not set to an instance of an object.--   at Glimpse.Ado.Model.ConnectionMetadata.RegiserTransactionStart(TransactionMetadata transaction)
   at Glimpse.Ado.Model.MessageAggregator.AggregateTransactionBegan()
   at Glimpse.Ado.Model.MessageAggregator.Aggregate()
   at Glimpse.Ado.Tab.SQL.GetData(ITabContext context)
   at Glimpse.Core.Framework.GlimpseRuntime.ExecuteTabs(RuntimeEvent runtimeEvent)

**Comment by avanderhoorn** [comment] 2015-04-23 23:11
Are you using transactions in you app?

**Comment by avanderhoorn** [comment] 2015-04-23 23:13
Also does this look like you issue - #772

**Comment by lchong0412** [comment] 2015-04-27 22:13
Hi, I'm not using transactions, do I need to to use transactions in order for it to work?

**Comment by avanderhoorn** [comment] 2015-05-06 15:11
No you shouldn't but I was just wondering because of the exception you put in. Does this look like you issue - #772?

**Comment by lchong0412** [comment] 2015-05-19 23:59
Yes, looks like the same exception I'm getting. Is there a fix for it already?

**Comment by avanderhoorn** [comment] 2015-05-26 18:49
The issue has been fixed but hasn't been pushed out yet. Trying to get a couple of last minute items addressed before releasing.

**Comment by avanderhoorn** [comment] 2015-05-26 18:49
Duplicate of #772

**Closed by avanderhoorn** 2015-05-26 18:49 UTC
